[package]
name = "enkei"
version = "0.1.0"
authors = ["comfysage", "isabelroses"]
license = "MIT"
description = "scriptable, curses-based, project tracker"
readme = "README.md"
homepage = "https://github.com/catgardens/enkei"
repository = "https://github.com/catgardens/enkei"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
cursive = "0.20.0"
